### ISSUE TITLE
Memory leaks in stag library

### ISSUE THREAD

**Issue by JasperTan97** [aica-technology/stag#5]
The STag library we forked from has been updated to fix the memory problems. We need to update it with the latest branch in [here](https://github.com/bbenligiray/stag/pull/32/files)

```console
Thread 48 "state_engine" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6cff9640 (LWP 755)]
0x00007ffff72c847e in free () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) backtrace
#0  0x00007ffff72c847e in free () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fff14d6ec0d in stag::EDLines::~EDLines (this=0x7fff5c275da0, __in_chrg=<optimized out>)
    at /home/ros2/ws/build/pose_detection/_deps/stag-src/include/stag/ED/EDLines.h:56
#2  0x00007fff14d6dbf9 in stag::EDInterface::~EDInterface (this=0x7fff58004308, 
    __in_chrg=<optimized out>)
```

Specifically: Edgemap.h line 42, EDlines.h line 56

**Comment by JasperTan97** [comment]
Close to facilitate #7
